---
ID: "ecb6c380-04fb-42e5-85a8-b0b33f0cc1a4"
Parent: "c1bca92b-dcaf-4422-8dca-de7bb9b8102e"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Deloitte/Foundation/Workflow/Triage Workflow Setting/Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160704T005724Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
