---
ID: "2d4365c6-7569-4594-9fcc-ade52eea98b9"
Parent: "e5c89eb3-60db-4c98-affc-82cb073e75d6"
Template: "e5c89eb3-60db-4c98-affc-82cb073e75d6"
Path: /sitecore/templates/Deloitte/Features/TemplatesModules/Hero Banner/Hero Banner Rendering Options/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160226T050759Z
