











//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated based on the Unicorn serialisation items
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable InconsistentNaming
namespace DSP.Business.Search
{
	using global::Sitecore.Data;

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
    public struct SitecoreTemplates
    {
	

		/// <summary>
		/// Automated Tag
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Features/Search/Automated Tag</para>	
		/// <para>ID: c6bfb493-0511-473c-9ad4-2e50fd845c2e</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Automated_Tag
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Features/Search/Automated Tag
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{c6bfb493-0511-473c-9ad4-2e50fd845c2e}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Features/Search/Automated Tag
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "c6bfb493-0511-473c-9ad4-2e50fd845c2e";

		}


		/// <summary>
		/// Content Tag
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Features/Search/Content Tag</para>	
		/// <para>ID: ccdcedcb-694e-495d-b78f-382d4edb3011</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Content_Tag
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Features/Search/Content Tag
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{ccdcedcb-694e-495d-b78f-382d4edb3011}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Features/Search/Content Tag
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "ccdcedcb-694e-495d-b78f-382d4edb3011";


			public struct HideFromDisplay
            {
				/// <summary>
				/// The HideFromDisplay field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// </summary>
                public const string FieldName = "HideFromDisplay";
            }


			public struct HideFromFacet
            {
				/// <summary>
				/// The HideFromFacet field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// </summary>
                public const string FieldName = "HideFromFacet";
            }

		}


		/// <summary>
		/// Sort Option
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Features/Search/Sort Option</para>	
		/// <para>ID: bdc3d199-d33a-4b6c-9b09-5dbf9c863c63</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Sort_Option
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Features/Search/Sort Option
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{bdc3d199-d33a-4b6c-9b09-5dbf9c863c63}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Features/Search/Sort Option
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "bdc3d199-d33a-4b6c-9b09-5dbf9c863c63";


			public struct Key
            {
				/// <summary>
				/// The Key field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "Key";
            }


			public struct Label
            {
				/// <summary>
				/// The Label field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "Label";
            }


			public struct Type
            {
				/// <summary>
				/// The Type field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "Type";
            }

		}

	}
}