---
ID: "5b4183e4-95dd-4132-95d6-500e43a363e2"
Parent: "62973a9a-efac-48a1-9e3e-c04f281ca807"
Template: "455a3e98-a627-4b40-8035-e683a0331ac7"
Path: /sitecore/templates/Deloitte/Foundation/Sections/Header/Header Content/LanguageConfiguration
DB: master
SharedFields:
- ID: "1eb8ae32-e190-44a6-968d-ed904c794ebf"
  Hint: Source
  Value: /sitecore/content/dspstarter/Configuration/Languages
- ID: "24cb32f0-e364-4f37-b400-0f2899097b5b"
  Hint: Enable Shared Language Fallback
  Type: Checkbox
  Value: 1
- ID: "ab162cc0-dc80-4abf-8871-998ee5d7ba32"
  Hint: Type
  Value: Droptree
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 400
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160821T055239Z
