---
ID: "b6bb3d0b-0be2-44a2-9d00-b40a600ac31c"
Parent: "4f71be78-6473-4a4b-8f17-3d2ad30c8b81"
Template: "4f71be78-6473-4a4b-8f17-3d2ad30c8b81"
Path: /sitecore/templates/Deloitte/Foundation/Sections/Header/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160106T034714Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
