---
ID: "75a2aae9-0628-4d6d-9ab0-93a1a1ec296b"
Parent: "d5c8bfbc-c281-4118-991a-b8a2de5c5561"
Template: "d5c8bfbc-c281-4118-991a-b8a2de5c5561"
Path: /sitecore/templates/Deloitte/Foundation/Common/Base Content Module/__Standard Values
DB: master
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{BF8104E9-729B-438B-836C-4DA0AE01C95D}"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20151125T040132Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
