---
ID: "6030a80f-0062-4a48-ac12-f5a4c8f6ceb7"
Parent: "c48157fc-cf79-40ca-93a4-153907512726"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Sort Order/Collection Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160205T051009Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
