---
ID: "23f8393d-0084-4d01-b88c-862c78da8781"
Parent: "eeec0925-8a48-48ed-bf84-cd9f5b93c1bb"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Collection Source/Collection Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160205T053440Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
