---
ID: "cc305cb8-07b7-46dc-9c05-9b3b7210d30f"
Parent: "f631b1b5-5058-4c74-9b5d-53a2d9d5aa29"
Template: "f631b1b5-5058-4c74-9b5d-53a2d9d5aa29"
Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Keywords/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160609T033246Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
