---
ID: "deb96520-383f-460e-a040-d6be5650b489"
Parent: "40dd6c8e-7553-4b29-a3c0-f6401b040a4b"
Template: "40dd6c8e-7553-4b29-a3c0-f6401b040a4b"
Path: /sitecore/templates/Deloitte/Features/TemplatesModules/Map/Map Module/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160609T121131Z
