











//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated based on the Unicorn serialisation items
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
// ReSharper disable InconsistentNaming
namespace DSP.Foundation
{
	using global::Sitecore.Data;

	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
    public struct SitecoreTemplates
    {
	

		/// <summary>
		/// Base Content Module
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Base Content Module</para>	
		/// <para>ID: d5c8bfbc-c281-4118-991a-b8a2de5c5561</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Base_Content_Module
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Base Content Module
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{d5c8bfbc-c281-4118-991a-b8a2de5c5561}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Base Content Module
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "d5c8bfbc-c281-4118-991a-b8a2de5c5561";

		}


		/// <summary>
		/// Base Page
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Base Page</para>	
		/// <para>ID: d60651a3-2b3d-4001-a779-549be7273c96</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Base_Page
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Base Page
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{d60651a3-2b3d-4001-a779-549be7273c96}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Base Page
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "d60651a3-2b3d-4001-a779-549be7273c96";

		}


		/// <summary>
		/// Base Tag
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Base Tag</para>	
		/// <para>ID: 9ea29c12-f902-4622-9a98-321a64d12028</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Base_Tag
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Base Tag
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{9ea29c12-f902-4622-9a98-321a64d12028}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Base Tag
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "9ea29c12-f902-4622-9a98-321a64d12028";

		}


		/// <summary>
		/// Tag Folder
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Tag Folder</para>	
		/// <para>ID: ca7a9ed6-848f-4d58-8db9-818bc7553dbd</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Tag_Folder
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Tag Folder
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{ca7a9ed6-848f-4d58-8db9-818bc7553dbd}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Tag Folder
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "ca7a9ed6-848f-4d58-8db9-818bc7553dbd";

		}


		/// <summary>
		/// Website
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Website</para>	
		/// <para>ID: 4f8c8e74-0218-4fc1-ae43-507bb81d40e2</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Website
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Website
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{4f8c8e74-0218-4fc1-ae43-507bb81d40e2}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Website
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "4f8c8e74-0218-4fc1-ae43-507bb81d40e2";

		}


		/// <summary>
		/// AGLS Meta Data
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Sections/AGLS Meta Data</para>	
		/// <para>ID: 7299c9c5-8ac3-47df-b7c0-21ef7999bb4b</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct AGLS_Meta_Data
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Sections/AGLS Meta Data
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{7299c9c5-8ac3-47df-b7c0-21ef7999bb4b}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Sections/AGLS Meta Data
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "7299c9c5-8ac3-47df-b7c0-21ef7999bb4b";


			public struct AglsCreator
            {
				/// <summary>
				/// The AglsCreator field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "AglsCreator";
                public const string FieldName_ToLowerInvariant = "aglscreator";

            }


			public struct AglsSubject
            {
				/// <summary>
				/// The AglsSubject field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "AglsSubject";
                public const string FieldName_ToLowerInvariant = "aglssubject";

            }

		}


		/// <summary>
		/// Common Meta Data
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Sections/Common Meta Data</para>	
		/// <para>ID: 34cb17e0-220c-4135-8223-2bc6c5a8f9d2</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Common_Meta_Data
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Sections/Common Meta Data
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{34cb17e0-220c-4135-8223-2bc6c5a8f9d2}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Sections/Common Meta Data
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "34cb17e0-220c-4135-8223-2bc6c5a8f9d2";


			public struct MetaAuthor
            {
				/// <summary>
				/// The MetaAuthor field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "MetaAuthor";
                public const string FieldName_ToLowerInvariant = "metaauthor";

            }


			public struct MetaBrowserTitle
            {
				/// <summary>
				/// The MetaBrowserTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "MetaBrowserTitle";
                public const string FieldName_ToLowerInvariant = "metabrowsertitle";

            }


			public struct MetaCanonical
            {
				/// <summary>
				/// The MetaCanonical field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "MetaCanonical";
                public const string FieldName_ToLowerInvariant = "metacanonical";

            }


			public struct MetaDescription
            {
				/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "MetaDescription";
                public const string FieldName_ToLowerInvariant = "metadescription";

            }


			public struct MetaKeywords
            {
				/// <summary>
				/// The MetaKeywords field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "MetaKeywords";
                public const string FieldName_ToLowerInvariant = "metakeywords";

            }


			public struct MetaRobots
            {
				/// <summary>
				/// The MetaRobots field.
				/// <para></para>
				/// <para>Field Type: Droplist</para>		
				/// </summary>
                public const string FieldName = "MetaRobots";
                public const string FieldName_ToLowerInvariant = "metarobots";

            }

		}


		/// <summary>
		/// Facebook App ID
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Sections/Facebook App ID</para>	
		/// <para>ID: ca5982b8-52c4-4c40-8b23-078e2de6c035</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Facebook_App_ID
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Sections/Facebook App ID
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{ca5982b8-52c4-4c40-8b23-078e2de6c035}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Sections/Facebook App ID
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "ca5982b8-52c4-4c40-8b23-078e2de6c035";


			public struct FacebookAppID
            {
				/// <summary>
				/// The FacebookAppID field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "FacebookAppID";
                public const string FieldName_ToLowerInvariant = "facebookappid";

            }

		}


		/// <summary>
		/// Featured Content
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Sections/Featured Content</para>	
		/// <para>ID: c9454f9a-aa8d-4581-a502-7463a1aa7d30</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Featured_Content
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Sections/Featured Content
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{c9454f9a-aa8d-4581-a502-7463a1aa7d30}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Sections/Featured Content
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "c9454f9a-aa8d-4581-a502-7463a1aa7d30";


			public struct FeatureImage
            {
				/// <summary>
				/// The FeatureImage field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// </summary>
                public const string FieldName = "FeatureImage";
                public const string FieldName_ToLowerInvariant = "featureimage";

            }


			public struct IsFeatured
            {
				/// <summary>
				/// The IsFeatured field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// </summary>
                public const string FieldName = "IsFeatured";
                public const string FieldName_ToLowerInvariant = "isfeatured";

            }

		}


		/// <summary>
		/// Header
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Sections/Header</para>	
		/// <para>ID: 4f71be78-6473-4a4b-8f17-3d2ad30c8b81</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Header
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Sections/Header
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{4f71be78-6473-4a4b-8f17-3d2ad30c8b81}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Sections/Header
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "4f71be78-6473-4a4b-8f17-3d2ad30c8b81";


			public struct GlobalPageTitle
            {
				/// <summary>
				/// The GlobalPageTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "GlobalPageTitle";
                public const string FieldName_ToLowerInvariant = "globalpagetitle";

            }


			public struct LanguageConfiguration
            {
				/// <summary>
				/// The LanguageConfiguration field.
				/// <para></para>
				/// <para>Field Type: Droptree</para>		
				/// </summary>
                public const string FieldName = "LanguageConfiguration";
                public const string FieldName_ToLowerInvariant = "languageconfiguration";

            }


			public struct LogoImage
            {
				/// <summary>
				/// The LogoImage field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// </summary>
                public const string FieldName = "LogoImage";
                public const string FieldName_ToLowerInvariant = "logoimage";

            }


			public struct SearchResultsPage
            {
				/// <summary>
				/// The SearchResultsPage field.
				/// <para></para>
				/// <para>Field Type: General Link</para>		
				/// </summary>
                public const string FieldName = "SearchResultsPage";
                public const string FieldName_ToLowerInvariant = "searchresultspage";

            }

		}


		/// <summary>
		/// Navigation
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Sections/Navigation</para>	
		/// <para>ID: a258d609-c687-4a8d-bd41-159173dbf343</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Navigation
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Sections/Navigation
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{a258d609-c687-4a8d-bd41-159173dbf343}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Sections/Navigation
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "a258d609-c687-4a8d-bd41-159173dbf343";


			public struct HideFromNavigation
            {
				/// <summary>
				/// The HideFromNavigation field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// </summary>
                public const string FieldName = "HideFromNavigation";
                public const string FieldName_ToLowerInvariant = "hidefromnavigation";

            }


			public struct HideFromSearch
            {
				/// <summary>
				/// The HideFromSearch field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// </summary>
                public const string FieldName = "HideFromSearch";
                public const string FieldName_ToLowerInvariant = "hidefromsearch";

            }


			public struct HideFromSitemap
            {
				/// <summary>
				/// The HideFromSitemap field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// </summary>
                public const string FieldName = "HideFromSitemap";
                public const string FieldName_ToLowerInvariant = "hidefromsitemap";

            }


			public struct NavigationTitle
            {
				/// <summary>
				/// The NavigationTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "NavigationTitle";
                public const string FieldName_ToLowerInvariant = "navigationtitle";

            }

		}


		/// <summary>
		/// Site setting
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Sections/Site setting</para>	
		/// <para>ID: ff4af87c-10a5-476a-add3-3a62f172d183</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Site_Setting
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Sections/Site setting
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{ff4af87c-10a5-476a-add3-3a62f172d183}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Sections/Site setting
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "ff4af87c-10a5-476a-add3-3a62f172d183";


			public struct SiteSettingItem
            {
				/// <summary>
				/// The SiteSettingItem field.
				/// <para></para>
				/// <para>Field Type: Droptree</para>		
				/// </summary>
                public const string FieldName = "SiteSettingItem";
                public const string FieldName_ToLowerInvariant = "sitesettingitem";

            }

		}


		/// <summary>
		/// Social Media Meta Data
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Sections/Social Media Meta Data</para>	
		/// <para>ID: e77a1b33-e53a-488d-a197-613bff03df6a</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Social_Media_Meta_Data
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Sections/Social Media Meta Data
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{e77a1b33-e53a-488d-a197-613bff03df6a}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Sections/Social Media Meta Data
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "e77a1b33-e53a-488d-a197-613bff03df6a";


			public struct SocialMediaImage
            {
				/// <summary>
				/// The SocialMediaImage field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// </summary>
                public const string FieldName = "SocialMediaImage";
                public const string FieldName_ToLowerInvariant = "socialmediaimage";

            }

		}


		/// <summary>
		/// Social Media
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Sections/Social Media</para>	
		/// <para>ID: 7f4a28bc-65df-4f60-ba6d-3f914f202353</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Social_Media
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Sections/Social Media
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{7f4a28bc-65df-4f60-ba6d-3f914f202353}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Sections/Social Media
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "7f4a28bc-65df-4f60-ba6d-3f914f202353";


			public struct SocialMediaTwitterAccount
            {
				/// <summary>
				/// The SocialMediaTwitterAccount field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "SocialMediaTwitterAccount";
                public const string FieldName_ToLowerInvariant = "socialmediatwitteraccount";

            }

		}


		/// <summary>
		/// Global Configuration
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Settings/Global Configuration</para>	
		/// <para>ID: 0728f1e2-6175-4370-82f5-e02eb22652c4</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Global_Configuration
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Settings/Global Configuration
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{0728f1e2-6175-4370-82f5-e02eb22652c4}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Settings/Global Configuration
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "0728f1e2-6175-4370-82f5-e02eb22652c4";

		}


		/// <summary>
		/// Key Value Setting
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Settings/Key Value Setting</para>	
		/// <para>ID: b9c68040-af98-4bc6-8000-7cbd79ce1f08</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Key_Value_Setting
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Settings/Key Value Setting
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{b9c68040-af98-4bc6-8000-7cbd79ce1f08}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Settings/Key Value Setting
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "b9c68040-af98-4bc6-8000-7cbd79ce1f08";


			public struct Help
            {
				/// <summary>
				/// The Help field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "Help";
                public const string FieldName_ToLowerInvariant = "help";

            }


			public struct Key
            {
				/// <summary>
				/// The Key field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "Key";
                public const string FieldName_ToLowerInvariant = "key";

            }


			public struct Value
            {
				/// <summary>
				/// The Value field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "Value";
                public const string FieldName_ToLowerInvariant = "value";

            }

		}


		/// <summary>
		/// Rich Content Setting
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Settings/Rich Content Setting</para>	
		/// <para>ID: 07391768-7140-48b8-8d8c-21885e364e24</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Rich_Content_Setting
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Settings/Rich Content Setting
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{07391768-7140-48b8-8d8c-21885e364e24}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Settings/Rich Content Setting
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "07391768-7140-48b8-8d8c-21885e364e24";


			public struct Help
            {
				/// <summary>
				/// The Help field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "Help";
                public const string FieldName_ToLowerInvariant = "help";

            }


			public struct Key
            {
				/// <summary>
				/// The Key field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "Key";
                public const string FieldName_ToLowerInvariant = "key";

            }


			public struct Value
            {
				/// <summary>
				/// The Value field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// </summary>
                public const string FieldName = "Value";
                public const string FieldName_ToLowerInvariant = "value";

            }

		}


		/// <summary>
		/// Setting Folder
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Settings/Setting Folder</para>	
		/// <para>ID: 4a2cefc3-510f-4a6a-94eb-d0108915fcea</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Setting_Folder
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Settings/Setting Folder
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{4a2cefc3-510f-4a6a-94eb-d0108915fcea}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Settings/Setting Folder
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "4a2cefc3-510f-4a6a-94eb-d0108915fcea";

		}


		/// <summary>
		/// Simple Setting
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Settings/Simple Setting</para>	
		/// <para>ID: 7564fb4f-21d5-4533-8b2c-bf307f341ede</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Simple_Setting
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Settings/Simple Setting
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{7564fb4f-21d5-4533-8b2c-bf307f341ede}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Settings/Simple Setting
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "7564fb4f-21d5-4533-8b2c-bf307f341ede";


			public struct Help
            {
				/// <summary>
				/// The Help field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "Help";
                public const string FieldName_ToLowerInvariant = "help";

            }

		}


		/// <summary>
		/// Apply Workflow Action
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Workflow/Apply Workflow Action</para>	
		/// <para>ID: 591c56ca-ba5f-4f96-a0c1-74f0ce4a1de6</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Apply_Workflow_Action
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Workflow/Apply Workflow Action
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{591c56ca-ba5f-4f96-a0c1-74f0ce4a1de6}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Workflow/Apply Workflow Action
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "591c56ca-ba5f-4f96-a0c1-74f0ce4a1de6";


			public struct TriageWorkflowConfigItems
            {
				/// <summary>
				/// The TriageWorkflowConfigItems field.
				/// <para></para>
				/// <para>Field Type: Droptree</para>		
				/// </summary>
                public const string FieldName = "TriageWorkflowConfigItems";
                public const string FieldName_ToLowerInvariant = "triageworkflowconfigitems";

            }

		}


		/// <summary>
		/// Triage Workflow Setting
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Workflow/Triage Workflow Setting</para>	
		/// <para>ID: c1bca92b-dcaf-4422-8dca-de7bb9b8102e</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Triage_Workflow_Setting
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Workflow/Triage Workflow Setting
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{c1bca92b-dcaf-4422-8dca-de7bb9b8102e}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Workflow/Triage Workflow Setting
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "c1bca92b-dcaf-4422-8dca-de7bb9b8102e";


			public struct StartPath
            {
				/// <summary>
				/// The StartPath field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "StartPath";
                public const string FieldName_ToLowerInvariant = "startpath";

            }


			public struct Workflow
            {
				/// <summary>
				/// The Workflow field.
				/// <para></para>
				/// <para>Field Type: Droplink</para>		
				/// </summary>
                public const string FieldName = "Workflow";
                public const string FieldName_ToLowerInvariant = "workflow";

            }

		}


		/// <summary>
		/// Collection Source
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Collection Source</para>	
		/// <para>ID: eeec0925-8a48-48ed-bf84-cd9f5b93c1bb</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Collection_Source
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Collection Source
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{eeec0925-8a48-48ed-bf84-cd9f5b93c1bb}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Collection Source
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "eeec0925-8a48-48ed-bf84-cd9f5b93c1bb";


			public struct CollectionSource
            {
				/// <summary>
				/// The CollectionSource field.
				/// <para></para>
				/// <para>Field Type: Droptree</para>		
				/// </summary>
                public const string FieldName = "CollectionSource";
                public const string FieldName_ToLowerInvariant = "collectionsource";

            }

		}


		/// <summary>
		/// General Description
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/General Description</para>	
		/// <para>ID: 4ea38d85-4d8a-4279-bd70-478775a83423</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct General_Description
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/General Description
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{4ea38d85-4d8a-4279-bd70-478775a83423}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/General Description
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "4ea38d85-4d8a-4279-bd70-478775a83423";


			public struct Description
            {
				/// <summary>
				/// The Description field.
				/// <para></para>
				/// <para>Field Type: Multi-Line Text</para>		
				/// </summary>
                public const string FieldName = "Description";
                public const string FieldName_ToLowerInvariant = "description";

            }

		}


		/// <summary>
		/// General Image Required
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/General Image Required</para>	
		/// <para>ID: c82475db-cd2b-4c75-8f35-7b5e2cc599ee</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct General_Image_Required
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/General Image Required
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{c82475db-cd2b-4c75-8f35-7b5e2cc599ee}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/General Image Required
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "c82475db-cd2b-4c75-8f35-7b5e2cc599ee";


			public struct GeneralImage
            {
				/// <summary>
				/// The GeneralImage field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// </summary>
                public const string FieldName = "GeneralImage";
                public const string FieldName_ToLowerInvariant = "generalimage";

            }

		}


		/// <summary>
		/// General Image
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/General Image</para>	
		/// <para>ID: 2793bf01-ac37-40d4-97aa-8f51c7c5c80b</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct General_Image
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/General Image
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{2793bf01-ac37-40d4-97aa-8f51c7c5c80b}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/General Image
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "2793bf01-ac37-40d4-97aa-8f51c7c5c80b";


			public struct GeneralImage
            {
				/// <summary>
				/// The GeneralImage field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// </summary>
                public const string FieldName = "GeneralImage";
                public const string FieldName_ToLowerInvariant = "generalimage";

            }

		}


		/// <summary>
		/// General Link
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/General Link</para>	
		/// <para>ID: bbe612bc-30e9-47fb-a556-e799db6da56d</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct General_Link
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/General Link
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{bbe612bc-30e9-47fb-a556-e799db6da56d}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/General Link
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "bbe612bc-30e9-47fb-a556-e799db6da56d";


			public struct GeneralLink
            {
				/// <summary>
				/// The GeneralLink field.
				/// <para></para>
				/// <para>Field Type: General Link with Search</para>		
				/// </summary>
                public const string FieldName = "GeneralLink";
                public const string FieldName_ToLowerInvariant = "generallink";

            }


			public struct MoreText
            {
				/// <summary>
				/// The MoreText field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "MoreText";
                public const string FieldName_ToLowerInvariant = "moretext";

            }

		}


		/// <summary>
		/// General Text Required
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/General Text Required</para>	
		/// <para>ID: 7142ba6a-14ad-4e90-b9c4-20dd7bbc727c</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct General_Text_Required
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/General Text Required
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{7142ba6a-14ad-4e90-b9c4-20dd7bbc727c}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/General Text Required
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "7142ba6a-14ad-4e90-b9c4-20dd7bbc727c";


			public struct GeneralText
            {
				/// <summary>
				/// The GeneralText field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// </summary>
                public const string FieldName = "GeneralText";
                public const string FieldName_ToLowerInvariant = "generaltext";

            }

		}


		/// <summary>
		/// General Text
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/General Text</para>	
		/// <para>ID: 4597abf0-8b18-454e-adcd-6a3256ccf2de</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct General_Text
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/General Text
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{4597abf0-8b18-454e-adcd-6a3256ccf2de}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/General Text
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "4597abf0-8b18-454e-adcd-6a3256ccf2de";


			public struct GeneralText
            {
				/// <summary>
				/// The GeneralText field.
				/// <para></para>
				/// <para>Field Type: Rich Text</para>		
				/// </summary>
                public const string FieldName = "GeneralText";
                public const string FieldName_ToLowerInvariant = "generaltext";

            }

		}


		/// <summary>
		/// Has Banner Image
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Banner Image</para>	
		/// <para>ID: 5e53f5c8-7f25-4cb1-b706-59c5331fbfcc</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Has_Banner_Image
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Banner Image
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{5e53f5c8-7f25-4cb1-b706-59c5331fbfcc}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Banner Image
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "5e53f5c8-7f25-4cb1-b706-59c5331fbfcc";


			public struct BannerImage
            {
				/// <summary>
				/// The BannerImage field.
				/// <para></para>
				/// <para>Field Type: Image</para>		
				/// </summary>
                public const string FieldName = "BannerImage";
                public const string FieldName_ToLowerInvariant = "bannerimage";

            }

		}


		/// <summary>
		/// Has Collection Facets
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Collection Facets</para>	
		/// <para>ID: c80c4ba5-ce45-4e44-b03c-c44bd2c479ed</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Has_Collection_Facets
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Collection Facets
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{c80c4ba5-ce45-4e44-b03c-c44bd2c479ed}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Collection Facets
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "c80c4ba5-ce45-4e44-b03c-c44bd2c479ed";


			public struct CollectionFacets
            {
				/// <summary>
				/// The CollectionFacets field.
				/// <para></para>
				/// <para>Field Type: Treelist</para>		
				/// </summary>
                public const string FieldName = "CollectionFacets";
                public const string FieldName_ToLowerInvariant = "collectionfacets";

            }

		}


		/// <summary>
		/// Has Dark Option
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Dark Option</para>	
		/// <para>ID: e3d4af5c-4f21-4bec-8328-5971f33680c2</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Has_Dark_Option
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Dark Option
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{e3d4af5c-4f21-4bec-8328-5971f33680c2}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Dark Option
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "e3d4af5c-4f21-4bec-8328-5971f33680c2";


			public struct IsDark
            {
				/// <summary>
				/// The IsDark field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// </summary>
                public const string FieldName = "IsDark";
                public const string FieldName_ToLowerInvariant = "isdark";

            }

		}


		/// <summary>
		/// Has Items Per Page
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Items Per Page</para>	
		/// <para>ID: 51900d98-7869-46fa-9549-8943d78b5d57</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Has_Items_Per_Page
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Items Per Page
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{51900d98-7869-46fa-9549-8943d78b5d57}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Items Per Page
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "51900d98-7869-46fa-9549-8943d78b5d57";


			public struct ShowItemsPerPage
            {
				/// <summary>
				/// The ShowItemsPerPage field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// </summary>
                public const string FieldName = "ShowItemsPerPage";
                public const string FieldName_ToLowerInvariant = "showitemsperpage";

            }

		}


		/// <summary>
		/// Has Keyword Facet
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Keyword Facet</para>	
		/// <para>ID: 1f5aaf97-0817-456e-b445-870861f3375b</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Has_Keyword_Facet
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Keyword Facet
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{1f5aaf97-0817-456e-b445-870861f3375b}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Keyword Facet
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "1f5aaf97-0817-456e-b445-870861f3375b";


			public struct ShowKeywordFacet
            {
				/// <summary>
				/// The ShowKeywordFacet field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// </summary>
                public const string FieldName = "ShowKeywordFacet";
                public const string FieldName_ToLowerInvariant = "showkeywordfacet";

            }

		}


		/// <summary>
		/// Has Sort Order Default Setting
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Sort Order Default Setting</para>	
		/// <para>ID: b016f525-e157-4249-9d82-4dbd6608029a</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Has_Sort_Order_Default_Setting
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Sort Order Default Setting
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{b016f525-e157-4249-9d82-4dbd6608029a}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Sort Order Default Setting
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "b016f525-e157-4249-9d82-4dbd6608029a";


			public struct SortOrderDefault
            {
				/// <summary>
				/// The SortOrderDefault field.
				/// <para></para>
				/// <para>Field Type: Droplink</para>		
				/// </summary>
                public const string FieldName = "SortOrderDefault";
                public const string FieldName_ToLowerInvariant = "sortorderdefault";

            }

		}


		/// <summary>
		/// Has Sort Order
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Sort Order</para>	
		/// <para>ID: c48157fc-cf79-40ca-93a4-153907512726</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Has_Sort_Order
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Sort Order
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{c48157fc-cf79-40ca-93a4-153907512726}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Sort Order
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "c48157fc-cf79-40ca-93a4-153907512726";


			public struct SortOrder
            {
				/// <summary>
				/// The SortOrder field.
				/// <para></para>
				/// <para>Field Type: Multilist</para>		
				/// </summary>
                public const string FieldName = "SortOrder";
                public const string FieldName_ToLowerInvariant = "sortorder";

            }

		}


		/// <summary>
		/// Has Tags
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Tags</para>	
		/// <para>ID: 02b5f3ec-4e44-4ce6-983d-da82a9b34039</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Has_Tags
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Tags
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{02b5f3ec-4e44-4ce6-983d-da82a9b34039}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Tags
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "02b5f3ec-4e44-4ce6-983d-da82a9b34039";


			public struct ContentTags
            {
				/// <summary>
				/// The ContentTags field.
				/// <para></para>
				/// <para>Field Type: Treelist</para>		
				/// </summary>
                public const string FieldName = "ContentTags";
                public const string FieldName_ToLowerInvariant = "contenttags";

            }

		}


		/// <summary>
		/// Media Metadata
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Media Metadata</para>	
		/// <para>ID: cd031d50-baff-48ed-b4e9-42c9545238fe</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Media_Metadata
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Media Metadata
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{cd031d50-baff-48ed-b4e9-42c9545238fe}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Media Metadata
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "cd031d50-baff-48ed-b4e9-42c9545238fe";


			public struct HideFromSearch
            {
				/// <summary>
				/// The HideFromSearch field.
				/// <para></para>
				/// <para>Field Type: Checkbox</para>		
				/// </summary>
                public const string FieldName = "HideFromSearch";
                public const string FieldName_ToLowerInvariant = "hidefromsearch";

            }


			public struct MetaDescription
            {
				/// <summary>
				/// The MetaDescription field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "MetaDescription";
                public const string FieldName_ToLowerInvariant = "metadescription";

            }

		}


		/// <summary>
		/// Query Featured Option
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Featured Option</para>	
		/// <para>ID: 42e1fb2f-41d8-43a6-bed4-0152f1a6844e</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Query_Featured_Option
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Featured Option
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{42e1fb2f-41d8-43a6-bed4-0152f1a6844e}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Featured Option
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "42e1fb2f-41d8-43a6-bed4-0152f1a6844e";


			public struct QueryFeaturedOption
            {
				/// <summary>
				/// The QueryFeaturedOption field.
				/// <para></para>
				/// <para>Field Type: Enum List</para>		
				/// </summary>
                public const string FieldName = "QueryFeaturedOption";
                public const string FieldName_ToLowerInvariant = "queryfeaturedoption";

            }

		}


		/// <summary>
		/// Query Keywords
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Keywords</para>	
		/// <para>ID: f631b1b5-5058-4c74-9b5d-53a2d9d5aa29</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Query_Keywords
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Keywords
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{f631b1b5-5058-4c74-9b5d-53a2d9d5aa29}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Keywords
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "f631b1b5-5058-4c74-9b5d-53a2d9d5aa29";


			public struct QueryKeywords
            {
				/// <summary>
				/// The QueryKeywords field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "QueryKeywords";
                public const string FieldName_ToLowerInvariant = "querykeywords";

            }

		}


		/// <summary>
		/// Query Path
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Path</para>	
		/// <para>ID: b762278d-3d87-4462-b933-0682a3292c18</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Query_Path
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Path
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{b762278d-3d87-4462-b933-0682a3292c18}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Path
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "b762278d-3d87-4462-b933-0682a3292c18";


			public struct QueryPath
            {
				/// <summary>
				/// The QueryPath field.
				/// <para></para>
				/// <para>Field Type: Treelist</para>		
				/// </summary>
                public const string FieldName = "QueryPath";
                public const string FieldName_ToLowerInvariant = "querypath";

            }

		}


		/// <summary>
		/// Query Pinned Results
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Pinned Results</para>	
		/// <para>ID: 8756c443-a6b7-47d9-b433-26db940c8897</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Query_Pinned_Results
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Pinned Results
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{8756c443-a6b7-47d9-b433-26db940c8897}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Pinned Results
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "8756c443-a6b7-47d9-b433-26db940c8897";


			public struct QueryPinnedResult1
            {
				/// <summary>
				/// The QueryPinnedResult1 field.
				/// <para></para>
				/// <para>Field Type: General Link with Search</para>		
				/// </summary>
                public const string FieldName = "QueryPinnedResult1";
                public const string FieldName_ToLowerInvariant = "querypinnedresult1";

            }


			public struct QueryPinnedResult2
            {
				/// <summary>
				/// The QueryPinnedResult2 field.
				/// <para></para>
				/// <para>Field Type: General Link with Search</para>		
				/// </summary>
                public const string FieldName = "QueryPinnedResult2";
                public const string FieldName_ToLowerInvariant = "querypinnedresult2";

            }


			public struct QueryPinnedResult3
            {
				/// <summary>
				/// The QueryPinnedResult3 field.
				/// <para></para>
				/// <para>Field Type: General Link with Search</para>		
				/// </summary>
                public const string FieldName = "QueryPinnedResult3";
                public const string FieldName_ToLowerInvariant = "querypinnedresult3";

            }

		}


		/// <summary>
		/// Query Skip Results
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Skip Results</para>	
		/// <para>ID: b6b76f21-3643-40c6-ac59-fac42344ff27</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Query_Skip_Results
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Skip Results
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{b6b76f21-3643-40c6-ac59-fac42344ff27}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Skip Results
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "b6b76f21-3643-40c6-ac59-fac42344ff27";


			public struct QuerySkip
            {
				/// <summary>
				/// The QuerySkip field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "QuerySkip";
                public const string FieldName_ToLowerInvariant = "queryskip";

            }

		}


		/// <summary>
		/// Query Sort Order
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Sort Order</para>	
		/// <para>ID: 28106c1a-f13c-43bd-8b6f-bdf6e741c314</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Query_Sort_Order
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Sort Order
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{28106c1a-f13c-43bd-8b6f-bdf6e741c314}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Sort Order
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "28106c1a-f13c-43bd-8b6f-bdf6e741c314";


			public struct QuerySortOption
            {
				/// <summary>
				/// The QuerySortOption field.
				/// <para></para>
				/// <para>Field Type: Droplist</para>		
				/// </summary>
                public const string FieldName = "QuerySortOption";
                public const string FieldName_ToLowerInvariant = "querysortoption";

            }

		}


		/// <summary>
		/// Query Tags Excluded
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Tags Excluded</para>	
		/// <para>ID: d622a26d-4f31-4a80-ab86-4f59e21fabd3</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Query_Tags_Excluded
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Tags Excluded
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{d622a26d-4f31-4a80-ab86-4f59e21fabd3}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Tags Excluded
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "d622a26d-4f31-4a80-ab86-4f59e21fabd3";


			public struct QueryTagsExcluded
            {
				/// <summary>
				/// The QueryTagsExcluded field.
				/// <para></para>
				/// <para>Field Type: Treelist</para>		
				/// </summary>
                public const string FieldName = "QueryTagsExcluded";
                public const string FieldName_ToLowerInvariant = "querytagsexcluded";

            }

		}


		/// <summary>
		/// Query Tags Operator
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Tags Operator</para>	
		/// <para>ID: bf472307-a8f5-41fa-ab74-630e3a96602f</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Query_Tags_Operator
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Tags Operator
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{bf472307-a8f5-41fa-ab74-630e3a96602f}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Tags Operator
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "bf472307-a8f5-41fa-ab74-630e3a96602f";


			public struct QueryTagsOperator
            {
				/// <summary>
				/// The QueryTagsOperator field.
				/// <para></para>
				/// <para>Field Type: Enum List</para>		
				/// </summary>
                public const string FieldName = "QueryTagsOperator";
                public const string FieldName_ToLowerInvariant = "querytagsoperator";

            }

		}


		/// <summary>
		/// Query Tags
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Tags</para>	
		/// <para>ID: 25d8c624-c99d-45f2-96eb-522d1101f20f</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Query_Tags
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Tags
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{25d8c624-c99d-45f2-96eb-522d1101f20f}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Tags
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "25d8c624-c99d-45f2-96eb-522d1101f20f";


			public struct QueryTags
            {
				/// <summary>
				/// The QueryTags field.
				/// <para></para>
				/// <para>Field Type: Treelist</para>		
				/// </summary>
                public const string FieldName = "QueryTags";
                public const string FieldName_ToLowerInvariant = "querytags";

            }

		}


		/// <summary>
		/// Query Take Results
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Take Results</para>	
		/// <para>ID: 7e79d03c-ed1b-4db2-8889-c97bbece0f19</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Query_Take_Results
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Take Results
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{7e79d03c-ed1b-4db2-8889-c97bbece0f19}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Take Results
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "7e79d03c-ed1b-4db2-8889-c97bbece0f19";


			public struct QuerySkip
            {
				/// <summary>
				/// The QuerySkip field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "QuerySkip";
                public const string FieldName_ToLowerInvariant = "queryskip";

            }


			public struct QueryTake
            {
				/// <summary>
				/// The QueryTake field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "QueryTake";
                public const string FieldName_ToLowerInvariant = "querytake";

            }

		}


		/// <summary>
		/// Query Templates
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Templates</para>	
		/// <para>ID: 21a696d3-a787-4edc-b1fb-76373a5cae2d</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Query_Templates
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Templates
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{21a696d3-a787-4edc-b1fb-76373a5cae2d}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Query Templates
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "21a696d3-a787-4edc-b1fb-76373a5cae2d";


			public struct QueryTemplates
            {
				/// <summary>
				/// The QueryTemplates field.
				/// <para></para>
				/// <para>Field Type: TreelistEx</para>		
				/// </summary>
                public const string FieldName = "QueryTemplates";
                public const string FieldName_ToLowerInvariant = "querytemplates";

            }

		}


		/// <summary>
		/// Short Description
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Short Description</para>	
		/// <para>ID: 307a76ca-f071-467e-88a9-4040c68f0d0e</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Short_Description
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Short Description
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{307a76ca-f071-467e-88a9-4040c68f0d0e}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Short Description
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "307a76ca-f071-467e-88a9-4040c68f0d0e";


			public struct ShortDescription
            {
				/// <summary>
				/// The ShortDescription field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "ShortDescription";
                public const string FieldName_ToLowerInvariant = "shortdescription";

            }

		}


		/// <summary>
		/// Short Title
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Short Title</para>	
		/// <para>ID: 3f64fa8f-2006-4534-aec1-d43ba065214d</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Short_Title
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Short Title
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{3f64fa8f-2006-4534-aec1-d43ba065214d}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Short Title
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "3f64fa8f-2006-4534-aec1-d43ba065214d";


			public struct ShortTitle
            {
				/// <summary>
				/// The ShortTitle field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "ShortTitle";
                public const string FieldName_ToLowerInvariant = "shorttitle";

            }

		}


		/// <summary>
		/// Title Required
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Title Required</para>	
		/// <para>ID: 6c8a8a14-21e9-4512-a34b-3c973b84c25d</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Title_Required
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Title Required
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{6c8a8a14-21e9-4512-a34b-3c973b84c25d}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Title Required
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "6c8a8a14-21e9-4512-a34b-3c973b84c25d";


			public struct Title
            {
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "Title";
                public const string FieldName_ToLowerInvariant = "title";

            }

		}


		/// <summary>
		/// Title
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Title</para>	
		/// <para>ID: 27a590ea-0a9e-45a7-a1e5-8b7205031fbc</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Title
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Title
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{27a590ea-0a9e-45a7-a1e5-8b7205031fbc}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Title
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "27a590ea-0a9e-45a7-a1e5-8b7205031fbc";


			public struct Title_Field
            {
				/// <summary>
				/// The Title field.
				/// <para></para>
				/// <para>Field Type: Single-Line Text</para>		
				/// </summary>
                public const string FieldName = "Title";
                public const string FieldName_ToLowerInvariant = "title";

            }

		}


		/// <summary>
		/// Has Banner Size Option
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Rendering Sections/Has Banner Size Option</para>	
		/// <para>ID: 372ff25b-1310-424b-b9f6-f1f8f40a44f8</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Has_Banner_Size_Option
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Rendering Sections/Has Banner Size Option
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{372ff25b-1310-424b-b9f6-f1f8f40a44f8}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Rendering Sections/Has Banner Size Option
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "372ff25b-1310-424b-b9f6-f1f8f40a44f8";


			public struct BannerSizeOption
            {
				/// <summary>
				/// The BannerSizeOption field.
				/// <para></para>
				/// <para>Field Type: Droplist</para>		
				/// </summary>
                public const string FieldName = "BannerSizeOption";
                public const string FieldName_ToLowerInvariant = "bannersizeoption";

            }

		}


		/// <summary>
		/// Has Border Option
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Rendering Sections/Has Border Option</para>	
		/// <para>ID: eb918425-81f5-45b6-b58a-eed1462cdc59</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Has_Border_Option
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Rendering Sections/Has Border Option
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{eb918425-81f5-45b6-b58a-eed1462cdc59}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Rendering Sections/Has Border Option
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "eb918425-81f5-45b6-b58a-eed1462cdc59";


			public struct BorderOption
            {
				/// <summary>
				/// The BorderOption field.
				/// <para></para>
				/// <para>Field Type: Droplist</para>		
				/// </summary>
                public const string FieldName = "BorderOption";
                public const string FieldName_ToLowerInvariant = "borderoption";

            }

		}


		/// <summary>
		/// Has Image Size Option
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Rendering Sections/Has Image Size Option</para>	
		/// <para>ID: da596f75-2419-4c30-8ef0-ef3a68ecf266</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Has_Image_Size_Option
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Rendering Sections/Has Image Size Option
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{da596f75-2419-4c30-8ef0-ef3a68ecf266}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Rendering Sections/Has Image Size Option
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "da596f75-2419-4c30-8ef0-ef3a68ecf266";


			public struct ImageSizeOption
            {
				/// <summary>
				/// The ImageSizeOption field.
				/// <para></para>
				/// <para>Field Type: Droplist</para>		
				/// </summary>
                public const string FieldName = "ImageSizeOption";
                public const string FieldName_ToLowerInvariant = "imagesizeoption";

            }

		}


		/// <summary>
		/// Has Text Background Option
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Rendering Sections/Has Text Background Option</para>	
		/// <para>ID: a1ad3c0f-3d76-4d53-9d1a-761911296efa</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Has_Text_Background_Option
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Rendering Sections/Has Text Background Option
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{a1ad3c0f-3d76-4d53-9d1a-761911296efa}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Rendering Sections/Has Text Background Option
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "a1ad3c0f-3d76-4d53-9d1a-761911296efa";


			public struct TextBackgroundOption
            {
				/// <summary>
				/// The TextBackgroundOption field.
				/// <para></para>
				/// <para>Field Type: Droplist</para>		
				/// </summary>
                public const string FieldName = "TextBackgroundOption";
                public const string FieldName_ToLowerInvariant = "textbackgroundoption";

            }

		}


		/// <summary>
		/// Has Text Position Option
		/// <para></para>
		/// <para>Path: /sitecore/templates/Deloitte/Foundation/Common/Rendering Sections/Has Text Position Option</para>	
		/// <para>ID: 03099e47-cb52-4aee-8686-4fb138565e03</para>	
		/// </summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
		public struct Has_Text_Position_Option
        {
			/// <summary>
			/// The ID for /sitecore/templates/Deloitte/Foundation/Common/Rendering Sections/Has Text Position Option
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
            public static ID Id = new ID("{03099e47-cb52-4aee-8686-4fb138565e03}");
			/// <summary>
			/// The TemplateId string for /sitecore/templates/Deloitte/Foundation/Common/Rendering Sections/Has Text Position Option
			/// </summary>
			[global::System.CodeDom.Compiler.GeneratedCodeAttribute("RainbowCodeGeneration", "1.0")]
			public const string TemplateId = "03099e47-cb52-4aee-8686-4fb138565e03";


			public struct TextPositionOption
            {
				/// <summary>
				/// The TextPositionOption field.
				/// <para></para>
				/// <para>Field Type: Droplist</para>		
				/// </summary>
                public const string FieldName = "TextPositionOption";
                public const string FieldName_ToLowerInvariant = "textpositionoption";

            }

		}

	}
}