---
ID: "5b14a6b4-d0eb-42bd-bdd2-6f037d152321"
Parent: "afcdc15b-f826-43b4-bdf7-c2b3b0212c53"
Template: "afcdc15b-f826-43b4-bdf7-c2b3b0212c53"
Path: /sitecore/templates/Deloitte/Features/TemplatesModules/Map/Map API Key/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160615T100921Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
