---
ID: "8ad6c428-d141-4e06-b58d-7840ba151159"
Parent: "1f5aaf97-0817-456e-b445-870861f3375b"
Template: "e269fbb5-3750-427a-9149-7aa950b49301"
Path: /sitecore/templates/Deloitte/Foundation/Common/Field Sections/Has Keyword Facet/Collection Settings
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160205T053125Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
