---
ID: "7b3c15fe-d903-4ca6-b7f0-162b4eb89b4c"
Parent: "3600300a-fd37-496d-b852-1129193e52ad"
Template: "3600300a-fd37-496d-b852-1129193e52ad"
Path: /sitecore/templates/Deloitte/Features/TemplatesModules/Footer/Social Media Link/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160125T013330Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
