---
ID: "e12fe25e-cceb-4dbd-a107-3bb2161a6667"
Parent: "d2632f2a-a347-466c-a2fe-96aa71d0e4eb"
Template: "d2632f2a-a347-466c-a2fe-96aa71d0e4eb"
Path: /sitecore/templates/Deloitte/Features/TemplatesModules/Download Links/Download Links Item/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160120T022331Z
