---
ID: "d42e9416-4e41-41da-9403-119618f30773"
Parent: "14fa946a-f92a-4b3b-be90-c9540d91d233"
Template: "14fa946a-f92a-4b3b-be90-c9540d91d233"
Path: /sitecore/templates/Deloitte/Features/TemplatesModules/Related Links/Related Link Item/__Standard Values
DB: master
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20150510T030053Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
