---
ID: "d28ad321-2f82-4cbf-b777-11217c32467f"
Parent: "7d55dda4-3c63-4753-979c-2071bc9630ce"
Template: "7d55dda4-3c63-4753-979c-2071bc9630ce"
Path: /sitecore/templates/Deloitte/Features/TemplatesModules/Footer/Footer/__Standard Values
DB: master
SharedFields:
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Type: Checkbox
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20160125T024800Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: sitecore\admin
